from models.azienda import AziendaModel
from models.tipoAzienda import TipoAziendaModel
from models.puntoVendita import PuntoVenditaModel
from models.tipoPuntoVendita import TipoPuntoVenditaModel
from models.campagna import CampagnaModel
from models.premio import PremioModel
from models.tessera import TesseraModel
from models.consumatore import ConsumatoreModel
from models.acquisto import AcquistoModel